
import { GoogleGenAI } from "@google/genai";
import { Match, Team } from "../types";

export const getMatchAnalysis = async (match: Match, teams: Team[]) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const team1 = teams.find(t => t.id === match.team1Id)?.name;
    const team2 = teams.find(t => t.id === match.team2Id)?.name;
    
    const prompt = `
      Analyze this cricket match result and provide a short, professional summary.
      Match: ${team1} vs ${team2}
      Total Overs: ${match.totalOvers}
      Innings 1 Score: ${match.innings[0]?.deliveries.reduce((a, b) => a + b.runs + b.extraRuns, 0)}/${match.innings[0]?.deliveries.filter(d => d.isWicket).length}
      Innings 2 Score: ${match.innings[1]?.deliveries.reduce((a, b) => a + b.runs + b.extraRuns, 0)}/${match.innings[1]?.deliveries.filter(d => d.isWicket).length}
      Winner: ${teams.find(t => t.id === match.winnerId)?.name || 'N/A'}
      
      Please provide:
      1. A catchy headline.
      2. Key turning point analysis.
      3. Top performer mention.
      Keep it under 150 words.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
    });

    return response.text;
  } catch (error) {
    console.error("AI Analysis failed:", error);
    return "Analysis unavailable at this moment.";
  }
};

// Fix: Implement and export editTournamentImage for image editing capabilities.
// Uses gemini-2.5-flash-image for standard image manipulation.
export const editTournamentImage = async (base64Data: string, mimeType: string, prompt: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  // Ensure we only pass the raw base64 data to the API by removing prefix if present.
  const data = base64Data.includes(',') ? base64Data.split(',')[1] : base64Data;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: data,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  // Iterate through parts to find the generated image data returned by the model.
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by the AI model.");
};

// Fix: Implement and export generateTournamentArt for high-quality creative art.
// Uses gemini-3-pro-image-preview for high quality and resolution.
export const generateTournamentArt = async (prompt: string, aspectRatio: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        // aspectRatio must be one of: "1:1", "3:4", "4:3", "9:16", "16:9".
        aspectRatio: aspectRatio as any,
        imageSize: "1K"
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No art generated by the AI model.");
};

// Fix: Implement and export searchCricketInfo with Google Search grounding.
// Fetches real-time cricket intelligence and extracts source URLs.
export const searchCricketInfo = async (query: string): Promise<{ text: string, sources: { title: string, uri: string }[] }> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: query,
    config: {
      tools: [{ googleSearch: {} }],
    },
  });

  const text = response.text || '';
  const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
  
  // Extract website URLs from grounding chunks as required for Search Grounding.
  const sources = groundingChunks
    .filter((chunk: any) => chunk.web)
    .map((chunk: any) => ({
      title: chunk.web.title || 'Verified Source',
      uri: chunk.web.uri,
    }));

  return { text, sources };
};
